name: Byron CI Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    strategy:
      matrix:
        include:
          - os: windows-latest
            variant: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Byron
        shell: powershell
        if: matrix.os == 'windows-latest'
        run: |                  
          $file_name = "qldbShellInGitHub"
          $complete_filename = $file_name.msi
          # Push unsigned MSI to S3
          $put_object_response=( aws s3api put-object --bucket ${{ secrets.AWS_UNSIGNED_BUCKET }} --key ${{ secrets.AWS_KEY }} --body $complete_filename --acl bucket-owner-full-control ) | ConvertFrom-Json 
          
          echo "put object response"
          echo $put_object_response
          
          $version_id = $put_object_response.VersionId
          
          echo "version_id"
          echo $version_id
          
